### ISSUE TITLE
Too many strings with german language

### ISSUE THREAD

**Issue by way2ecommerce** [mageplaza/magento-2-spanish-language-pack#8]
Too many strings with german language, this is a patch with corrections ...

[0001-Update-Language-Pack.zip](https://github.com/mageplaza/magento-2-spanish-language-pack/files/2828505/0001-Update-Language-Pack.zip)

**Comment by MyoDaisy** [comment]
I see many strings have been fixed in latest version of Spanish Language Pack . Please update it and check again.

If you think there are still incorrect phrase, please follow the instructions in this link to contribute: 
[https://github.com/mageplaza/magento-2-spanish-language-pack/blob/master/HOW-TO-CONTRIBUTE.md](https://github.com/mageplaza/magento-2-spanish-language-pack/blob/master/HOW-TO-CONTRIBUTE.md)

Please note only add untranslated strings or edit incorrectly translated strings, do not add properly translated strings already available.

Thank you so much for your contributions.
